default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: my_blog_development
test:
  <<: *default
  database: my_blog_test
production:
  <<: *default
  database: my_blog_production
  username: ettore-bernardi
  password: <%= ENV['C4t3t0'] %>
